name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Copy Cesium assets
        run: |
          mkdir -p public/cesium
          cp version.txt public/version.txt
          cp -r node_modules/cesium/Build/Cesium/Workers public/cesium/Workers
          cp -r node_modules/cesium/Build/Cesium/ThirdParty public/cesium/ThirdParty
          cp -r node_modules/cesium/Build/Cesium/Assets public/cesium/Assets
          cp -r node_modules/cesium/Build/Cesium/Widgets public/cesium/Widgets

      - name: Build
        run: npm run build
        env:
          REACT_APP_CESIUM_TOKEN: ${{ secrets.REACT_APP_CESIUM_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build